FROM node:16-alpine

WORKDIR '/app'

COPY package.json .
RUN npm install --unsafe-perm=true --allow-root

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

COPY ./ ./

CMD ["npm", "run", "start"]
